# build environment
FROM node:14-stretch as build
WORKDIR /app
##COPY package.json ./
##COPY yarn.lock ./
git clone https://github.com/leoBergerot/reef-supervisor-api.git
RUN yarn install --pure-lockfile --production[true] --silent --non-interactive
#COPY . ./
RUN yarn build

# production environment
FROM node:14-alpine
WORKDIR /app
COPY --from=build /app ./
CMD ["yarn", "start:prod"]

